container_67: {
  label: "Customer's mobile device\n[Deployment Node: Apple iOS or Android]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    stroke: "#888888"
    multiple: false
    font-color: "#000000"
    font-size: 24
  }
  container_68: {
    label: "Mobile App"
    shape: rectangle
    style: {
      fill: "#438dd5"
      stroke: "#2e6295"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
}
container_69: {
  label: "Customer's computer\n[Deployment Node: Microsoft Windows or Apple macOS]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    stroke: "#888888"
    multiple: false
    font-color: "#000000"
    font-size: 24
  }
  container_70: {
    label: "Web Browser\n[Deployment Node: Chrome, Firefox, Safari, or Edge]"
    shape: rectangle
    style: {
      fill: "#ffffff"
      stroke: "#888888"
      multiple: false
      font-color: "#000000"
      font-size: 24
    }
    container_71: {
      label: "Single-Page Application"
      shape: rectangle
      style: {
        fill: "#438dd5"
        stroke: "#2e6295"
        multiple: false
        font-color: "#ffffff"
        font-size: 24
      }
    }
  }
}
container_72: {
  label: "Big Bank plc\n[Deployment Node: Big Bank plc data center]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    stroke: "#888888"
    multiple: false
    font-color: "#000000"
    font-size: 24
  }
  container_79: {
    label: "bigbank-api***\n[Deployment Node: Ubuntu 16.04 LTS]"
    shape: rectangle
    style: {
      fill: "#ffffff"
      stroke: "#888888"
      multiple: true
      font-color: "#000000"
      font-size: 24
    }
    container_80: {
      label: "Apache Tomcat\n[Deployment Node: Apache Tomcat 8.x]"
      shape: rectangle
      style: {
        fill: "#ffffff"
        stroke: "#888888"
        multiple: false
        font-color: "#000000"
        font-size: 24
      }
      container_81: {
        label: "API Application"
        shape: rectangle
        style: {
          fill: "#438dd5"
          stroke: "#2e6295"
          multiple: false
          font-color: "#ffffff"
          font-size: 24
        }
      }
    }
  }
  container_85: {
    label: "bigbank-db01\n[Deployment Node: Ubuntu 16.04 LTS]"
    shape: rectangle
    style: {
      fill: "#ffffff"
      stroke: "#888888"
      multiple: false
      font-color: "#000000"
      font-size: 24
    }
    container_86: {
      label: "Oracle - Primary\n[Deployment Node: Oracle 12c]"
      shape: rectangle
      style: {
        fill: "#ffffff"
        stroke: "#888888"
        multiple: false
        font-color: "#000000"
        font-size: 24
      }
      container_87: {
        label: "Database"
        shape: cylinder
        style: {
          fill: "#438dd5"
          stroke: "#2e6295"
          multiple: false
          font-color: "#ffffff"
          font-size: 24
        }
      }
    }
  }
  container_89: {
    label: "bigbank-db02\n[Deployment Node: Ubuntu 16.04 LTS]"
    shape: rectangle
    style: {
      fill: "#ffffff"
      stroke: "#888888"
      multiple: false
      font-color: "#000000"
      font-size: 24
    }
    container_90: {
      label: "Oracle - Secondary\n[Deployment Node: Oracle 12c]"
      shape: rectangle
      style: {
        fill: "#ffffff"
        stroke: "#888888"
        multiple: false
        font-color: "#000000"
        font-size: 24
      }
      container_91: {
        label: "Database"
        shape: cylinder
        style: {
          fill: "#438dd5"
          stroke: "#2e6295"
          multiple: false
          font-color: "#ffffff"
          font-size: 24
        }
      }
    }
  }
  container_73: {
    label: "bigbank-prod001\n[Deployment Node]"
    shape: rectangle
    style: {
      fill: "#ffffff"
      stroke: "#888888"
      multiple: false
      font-color: "#000000"
      font-size: 24
    }
    container_74: {
      label: "Mainframe Banking System"
      shape: rectangle
      style: {
        fill: "#999999"
        stroke: "#6b6b6b"
        multiple: false
        font-color: "#ffffff"
        font-size: 24
      }
    }
  }
  container_75: {
    label: "bigbank-web***\n[Deployment Node: Ubuntu 16.04 LTS]"
    shape: rectangle
    style: {
      fill: "#ffffff"
      stroke: "#888888"
      multiple: true
      font-color: "#000000"
      font-size: 24
    }
    container_76: {
      label: "Apache Tomcat\n[Deployment Node: Apache Tomcat 8.x]"
      shape: rectangle
      style: {
        fill: "#ffffff"
        stroke: "#888888"
        multiple: false
        font-color: "#000000"
        font-size: 24
      }
      container_77: {
        label: "Web Application"
        shape: rectangle
        style: {
          fill: "#438dd5"
          stroke: "#2e6295"
          multiple: false
          font-color: "#ffffff"
          font-size: 24
        }
      }
    }
  }
}
container_72.container_75.container_76.container_77 -> container_69.container_70.container_71 {
  label: "Delivers to the customer's web browser"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_67.container_68 -> container_72.container_79.container_80.container_81 {
  label: "Makes API calls to\n[JSON/HTTPS]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_69.container_70.container_71 -> container_72.container_79.container_80.container_81 {
  label: "Makes API calls to\n[JSON/HTTPS]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_72.container_79.container_80.container_81 -> container_72.container_73.container_74 {
  label: "Makes API calls to\n[XML/HTTPS]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_72.container_79.container_80.container_81 -> container_72.container_85.container_86.container_87 {
  label: "Reads from and writes to\n[JDBC]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_72.container_79.container_80.container_81 -> container_72.container_89.container_90.container_91 {
  label: "Reads from and writes to\n[JDBC]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_72.container_85.container_86 -> container_72.container_89.container_90 {
  label: "Replicates data to"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
