container_1: {
  label: "Personal Banking Customer\n[Person]"
  shape: person
  style: {
    fill: "#08427b"
    stroke: "#052e56"
    multiple: false
    font-color: "#ffffff"
    font-size: 22
  }
}
container_4: {
  label: "Mainframe Banking System\n[Software System]"
  shape: rectangle
  style: {
    fill: "#999999"
    stroke: "#6b6b6b"
    multiple: false
    font-color: "#ffffff"
    font-size: 24
  }
}
container_6: {
  label: "E-mail System\n[Software System]"
  shape: rectangle
  style: {
    fill: "#999999"
    stroke: "#6b6b6b"
    multiple: false
    font-color: "#ffffff"
    font-size: 24
  }
}

container_2: {
  label: "Internet Banking System\n[Software System]"
  style: {
    fill: "#1168bd"
    stroke: "#0b4884"
    multiple: false
    font-color: "#ffffff"
    font-size: 24
  }
  container_17: {
    label: "Single-Page Application\n[Container: JavaScript and Angular]"
    shape: rectangle
    style: {
      fill: "#438dd5"
      stroke: "#2e6295"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
  container_18: {
    label: "Mobile App\n[Container: Xamarin]"
    shape: rectangle
    style: {
      fill: "#438dd5"
      stroke: "#2e6295"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
  container_19: {
    label: "Web Application\n[Container: Java and Spring MVC]"
    shape: rectangle
    style: {
      fill: "#438dd5"
      stroke: "#2e6295"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
  container_20: {
    label: "API Application\n[Container: Java and Spring MVC]"
    shape: rectangle
    style: {
      fill: "#438dd5"
      stroke: "#2e6295"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
  container_21: {
    label: "Database\n[Container: Oracle Database Schema]"
    shape: cylinder
    style: {
      fill: "#438dd5"
      stroke: "#2e6295"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
}
container_1 -> container_2.container_19 {
  label: "Visits bigbank.com/ib using\n[HTTPS]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> container_2.container_17 {
  label: "Views account balances, and makes payments using"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> container_2.container_18 {
  label: "Views account balances, and makes payments using"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_2.container_19 -> container_2.container_17 {
  label: "Delivers to the customer's web browser"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_2.container_20 -> container_2.container_21 {
  label: "Reads from and writes to\n[JDBC]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_2.container_20 -> container_4 {
  label: "Makes API calls to\n[XML/HTTPS]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_2.container_20 -> container_6 {
  label: "Sends e-mail using\n[SMTP]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_2.container_17 -> container_2.container_20 {
  label: "Makes API calls to\n[JSON/HTTPS]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_2.container_18 -> container_2.container_20 {
  label: "Makes API calls to\n[JSON/HTTPS]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_6 -> container_1 {
  label: "Sends e-mails to"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
