"enterprise_Big Bank plc": {
  label: "Big Bank plc"
  style: {
    fill: white
    stroke: black
  }
  container_12: {
    label: "Customer Service Staff\n[Person]"
    shape: person
    style: {
      fill: "#999999"
      stroke: "#6b6b6b"
      multiple: false
      font-color: "#ffffff"
      font-size: 22
    }
  }
  container_15: {
    label: "Back Office Staff\n[Person]"
    shape: person
    style: {
      fill: "#999999"
      stroke: "#6b6b6b"
      multiple: false
      font-color: "#ffffff"
      font-size: 22
    }
  }
  container_2: {
    label: "Internet Banking System\n[Software System]"
    shape: rectangle
    style: {
      fill: "#1168bd"
      stroke: "#0b4884"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
  container_4: {
    label: "Mainframe Banking System\n[Software System]"
    shape: rectangle
    style: {
      fill: "#999999"
      stroke: "#6b6b6b"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
  container_6: {
    label: "E-mail System\n[Software System]"
    shape: rectangle
    style: {
      fill: "#999999"
      stroke: "#6b6b6b"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
  container_9: {
    label: "ATM\n[Software System]"
    shape: rectangle
    style: {
      fill: "#999999"
      stroke: "#6b6b6b"
      multiple: false
      font-color: "#ffffff"
      font-size: 24
    }
  }
}
container_1: {
  label: "Personal Banking Customer\n[Person]"
  shape: person
  style: {
    fill: "#08427b"
    stroke: "#052e56"
    multiple: false
    font-color: "#ffffff"
    font-size: 22
  }
}

"enterprise_Big Bank plc".container_9 -> "enterprise_Big Bank plc".container_4 {
  label: "Uses"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> "enterprise_Big Bank plc".container_9 {
  label: "Withdraws cash using"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_12 -> "enterprise_Big Bank plc".container_4 {
  label: "Uses"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> "enterprise_Big Bank plc".container_12 {
  label: "Asks questions to\n[Telephone]"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_15 -> "enterprise_Big Bank plc".container_4 {
  label: "Uses"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> "enterprise_Big Bank plc".container_2 {
  label: "Views account balances, and makes payments using"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_2 -> "enterprise_Big Bank plc".container_4 {
  label: "Gets account information from, and makes payments using"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_2 -> "enterprise_Big Bank plc".container_6 {
  label: "Sends e-mail using"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_6 -> container_1 {
  label: "Sends e-mails to"
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
