container_3: {
  label: "C\n[Software System]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    stroke: "#9a9a9a"
    multiple: false
    font-color: "#000000"
    font-size: 24
  }
}

container_6: {
  label: "F\n[Container]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    stroke: "#9a9a9a"
    multiple: false
    font-color: "#000000"
    font-size: 24
  }
  "group_Group 4": {
    label: "Group 4"
    style: {
      fill: white
      stroke: black
    }
    container_8: {
      label: "H\n[Component]"
      shape: rectangle
      style: {
        fill: "#dddddd"
        stroke: "#9a9a9a"
        multiple: false
        font-color: "#000000"
        font-size: 24
      }
    }
  }
  container_7: {
    label: "G\n[Component]"
    shape: rectangle
    style: {
      fill: "#dddddd"
      stroke: "#9a9a9a"
      multiple: false
      font-color: "#000000"
      font-size: 24
    }
  }
}
container_3 -> container_6.container_7 {
  label: ""
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_3 -> container_6."group_Group 4".container_8 {
  label: ""
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
