"enterprise_Enterprise": {
  label: "Enterprise"
  style: {
    fill: white
    stroke: black
  }
  "group_Group 2": {
    label: "Group 2"
    style: {
      fill: white
      stroke: black
    }
    container_4: {
      label: "D\n[Software System]"
      shape: rectangle
      style: {
        fill: "#dddddd"
        stroke: "#9a9a9a"
        multiple: false
        font-color: "#000000"
        font-size: 24
      }
    }
  }
  container_3: {
    label: "C\n[Software System]"
    shape: rectangle
    style: {
      fill: "#dddddd"
      stroke: "#9a9a9a"
      multiple: false
      font-color: "#000000"
      font-size: 24
    }
  }
}
"group_Group 1": {
  label: "Group 1"
  style: {
    fill: white
    stroke: black
  }
  container_2: {
    label: "B\n[Software System]"
    shape: rectangle
    style: {
      fill: "#dddddd"
      stroke: "#9a9a9a"
      multiple: false
      font-color: "#000000"
      font-size: 24
    }
  }
}
container_1: {
  label: "A\n[Software System]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    stroke: "#9a9a9a"
    multiple: false
    font-color: "#000000"
    font-size: 24
  }
}

"group_Group 1".container_2 -> "enterprise_Enterprise".container_3 {
  label: ""
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Enterprise".container_3 -> "enterprise_Enterprise"."group_Group 2".container_4 {
  label: ""
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> "group_Group 1".container_2 {
  label: ""
  style: {
    stroke: "#707070"
    stroke-width: 2
  }
}
