@startuml
set separator none
title D - F - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System(C, "C", "", $tags="")

Container_Boundary("D.F_boundary", "F", $tags="") {
  AddBoundaryTag("Group 4", $borderColor="#cccccc", $fontColor="#cccccc")
  Boundary(group_1, "Group 4", $tags="Group 4") {
    Component(D.F.H, "H", "", $tags="")
  }

  Component(D.F.G, "G", "", $tags="")
}

Rel_D(C, D.F.G, "", $tags="")
Rel_D(C, D.F.H, "", $tags="")

SHOW_LEGEND(true)
@enduml