@startuml
set separator none
title System Landscape

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Enterprise_Boundary(enterprise, "Enterprise") {
  AddBoundaryTag("Group 2", $borderColor="#cccccc", $fontColor="#cccccc")
  Boundary(group_1, "Group 2", $tags="Group 2") {
    System(D, "D", "", $tags="")
  }

  System(C, "C", "", $tags="")
}

AddBoundaryTag("Group 1", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_2, "Group 1", $tags="Group 1") {
  System_Ext(B, "B", "", $tags="")
}

System_Ext(A, "A", "", $tags="")

Rel_D(B, C, "", $tags="")
Rel_D(C, D, "", $tags="")
Rel_D(A, B, "", $tags="")

SHOW_LEGEND(true)
@enduml