@startuml
set separator none
title D - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(C, "C", "", $tags="")

System_Boundary("D_boundary", "D", $tags="") {
  AddBoundaryTag("Group 3", $borderColor="#cccccc", $fontColor="#cccccc")
  Boundary(group_1, "Group 3", $tags="Group 3") {
    Container(D.F, "F", "", $tags="")
  }

  Container(D.E, "E", "", $tags="")
}

Rel_D(C, D.E, "", $tags="", $link="")
Rel_D(C, D.F, "", $tags="", $link="")

SHOW_LEGEND(true)
@enduml
