@startuml
title D - F - Components

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System(C, "C", "", $tags="")

Container_Boundary("D.F_boundary", "F", $tags="") {
  Boundary(group_3, "Group 4") {
    Component(D.F.H, "H", "", $tags="")
  }

  Component(D.F.G, "G", "", $tags="")
}

Rel_D(C, D.F.G, "", $tags="")
Rel_D(C, D.F.H, "", $tags="")

SHOW_LEGEND(true)
@enduml